# Vectorization


### Paralle Computering Hardware implimenting matrix mulifications; like GPUs; some CPUs functions

#### ``` for loop ```

In [37]:
# for loop 
import numpy as np

x = np.array([200, 17])

W = np.array([
    [1,-3,5],
    [-2,4,-6]
])

b = np.array([-1,1,2],)

def g(x):
    return 1 / (1 + np.exp(-x))

print(W.shape)
def dense(a_in,W,b):
    units = W.shape[1]
    a_out = np.zeros(units)

    for j in range(units):
        w = W[:,j]
        z = np.dot(w,a_in) + b[j]
        
        a_out[j] = g(z)
    return a_out

print(np.around(dense(x,W,b)))

(2, 3)
[1. 0. 1.]


#### ``` matrix mulitification ```

In [2]:
import numpy as np
X = np.array([200, 17]) # 2D array

W = np.array([
    [1,-3,5],
    [-2,4,-6]
]) # 2x3 Matrix / 2D array

B = np.array([-1,1,2],) # 1x3 3D array

def g(x):
    return 1 / (1 + np.exp(-x))

def dense(A_in,W,B):
    # Z = np.matmul(A_in, W) + B # same with @ => np.matmul
    Z = A_in @ W + B
    A_out = g(Z)
    return A_out

print(np.around(dense(x,W,b)))

NameError: name 'x' is not defined

In [21]:
W = np.array([
    [3,5],
    [4,6]
])

A = np.array([
    [1,-1],
    [2,-2]
])

c = np.dot(A,W)
print(c)

[[-1 -1]
 [-2 -2]]


In [24]:
A.T @ W
# A @ W

array([[ 11,  17],
       [-11, -17]])