# Example for normalized


In [4]:
# import the essential lib
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)


In [8]:
adapt_data = np.array([1., 2., 3., 4., 5.], dtype='float32')
input_data = np.array([1., 2., 3.], dtype='float32')
layer = tf.keras.layers.Normalization(axis=None)
layer.adapt(adapt_data)
layer(input_data)
# array([-1.4142135, -0.70710677, 0.], dtype=float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.4142135 , -0.70710677,  0.        ], dtype=float32)>

In [12]:
print(np.max(adapt_data))

5.0


In [6]:
import numpy as np
import tensorflow as tf

# Define your data
adapt_data = np.array([1., 2., 3., 4., 5.], dtype='float32')
input_data = np.array([1., 2., 3.], dtype='float32')

# Create a Normalization layer
layer = tf.keras.layers.Normalization(axis=None)

# Adapt the data to the layer (calculate mean and variance)
layer.adapt(adapt_data)

# Use the layer on your data
normalized_data = layer(input_data)

print(normalized_data)


tf.Tensor([-1.4142135  -0.70710677  0.        ], shape=(3,), dtype=float32)
